apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: remix-jokes.test.stiforr.tech
  namespace: default
spec:
  ref:
    name: knative-service-{{ include "chart.fullname" . }}
    kind: Service
    apiVersion: serving.knative.dev/v1
  tls:
    secretName: knative-remix-jokes-tls