kind: Service
apiVersion: serving.knative.dev/v1
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    networking.knative.dev/httpOption: "redirected"
spec:
  template:
    spec:
      containers:
        - image: stiforr/remix-jokes