name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      with:
        install: true
    - name: Build the Docker image
      env:
        DATABASE_URL: file:./dev.db
        SESSION_SECRET: ${{ secrets.session_secret }}
      run: docker build . --file Dockerfile --tag remix-jokes:$(date +%s)
