name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      with:
        install: true
    - name: Build the Docker image
      run: docker build --build-arg SESSION_SECRET={{ secrets.session_secret }} --build-arg DATABASE_URL=file:./dev.db --file Dockerfile --tag remix-jokes:$(date +%s) .
